language: node_js
node_js:
- node
cache: yarn
deploy:
  provider: npm
  email: idmontie@gmail.com
  api_key:
    secure: eBXL8LJ5aoVauka79IMsE0TH4mlZZB16jq0uExLaTdBL8iIPxZ4T3J+gIyF+al2URCdJgQGNCY+CdHlgJRF1h0jkzWlIZliSj3Wm6ML1Nm/6xwYaQcmHW0ghDpUFDo26686OPK3eHq0g/ATeKMrsnymODR8RszB1aqGoI9kFXB+yJRR/Ijg7pAQqsbitYPYTaD2HhhKA5lRSJ2jMUIzFKTwvRHLmz/QEQTqUD6/uSaoin1ieuxvkHXoLlq7pC43aUf5mtGbI+LldhLywfNOw3TV9H6C4wiHzmUy/npvgoziORYSnNSxcWpcqdtcXGO+GDMPOZJosWeAzfezW0GhVV0/sHOgdLqESNnW8muRH25QvQsYJdAtNxWp8l5X4/eQDzNeGDScJOHB7DKubHBTU1vhpoSQ17iThsCxra8kBMrJRNQuuZCYaC1Z6HtnVE+JtCOZRo89CYVEhfLMcyQZqu8bMqyXdKL2QeMZcvwXkNG7z2sOdaeGysIXgHiDa5p7sdwIIb9UGWRRoAXxU4DSIisOkn65RfT7eQtEQbbTPuIDBzgqyd8qY20U4BDASPJ2NdCDCGxWUsxuYG1dY0K6nfbGU4Zjmt1k2xZkN0lZTdN208+l5pLms+XLWy/P8GfC+Xwy6eh98PSiZgLv3ashO7Y7++YPKyuDwm8t9j6OsFUc=
  edge: true
  on:
    tags: true
    repo: clarityhub/serverless-dynamodb-migrations
